add missing header for libc++ 14 after 54af645c2eab (#69)
In file included from src/wcm.cpp:1:
src/wcm.hpp:69:52: error: implicit instantiation of undefined template 'std::array<Gtk::Separator, 7>'
    std::array<Gtk::Separator, NUM_CATEGORIES - 1> separators;
                                                   ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^